### ISSUE TITLE
Fails to parse ISO/DATA docs

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#241]
There are a few ISO/DATA docs like [ISO/DATA 3:1977](https://www.iso.org/standard/3566.html) which this gem fails to parse:
```ruby
> Pubid::Iso::Identifier.parse 'ISO/DATA 3:1977'
/Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.8.7/lib/pubid/core/identifier.rb:33:in `resolve_identifier': cannot parse type DATA (Pubid::Core::Errors::ParseTypeError)
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.8.7/lib/pubid/core/identifier.rb:9:in `create'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-iso-0.6.1/lib/pubid/iso/identifier/base.rb:141:in `transform'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.8.7/lib/pubid/core/identifier/base.rb:139:in `parse'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-iso-0.6.1/lib/pubid/iso/identifier.rb:7:in `parse'
	from (irb):2:in `<main>'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/irb-1.11.0/exe/irb:9:in `<top (required)>'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/irb:25:in `load'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/irb:25:in `<main>'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `eval'
	from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by ronaldtse** [comment]
@mico can you please help handle this ASAP? @andrew2net is waiting. Thanks!

**Comment by mico** [comment]
@ronaldtse @andrew2net I cannot find any information or other identifiers for "DATA" type. I need full name of "DATA" type for class naming.

**Comment by andrew2net** [comment]
@mico I don't know what the "DATA" means. @ronaldtse can you explain?

**Comment by ronaldtse** [comment]
@mico Let's just call the "DATA" document type "Data".

Here's an example of the data previously published as "ISO DATA 1":
* https://www.iso.org/obp/ui/en/#iso:std:iso:tr:7468:ed-1:v1:en

So I think just calling it "Data" (full name) is fine.
