### ISSUE TITLE
URGENT! Fails to render URN

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-iso#263]
```ruby
> id = Pubid::Iso::Identifier.parse 'ISO 1101:1983/Ext 1:1983'
=> #<Pubid::Iso::Identifier::Extract:0x00000001052fa660 ...

> id.urn
/Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.12.3/lib/pubid/core/renderer/urn.rb:4:in `render_base': wrong number of arguments (given 3, expected 1) (ArgumentError)
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.12.3/lib/pubid/core/renderer/base.rb:36:in `block in prerender_params'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.12.3/lib/pubid/core/renderer/base.rb:33:in `each'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.12.3/lib/pubid/core/renderer/base.rb:33:in `map'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.12.3/lib/pubid/core/renderer/base.rb:33:in `prerender_params'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.12.3/lib/pubid/core/renderer/base.rb:20:in `prerender'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-iso-0.7.4/lib/pubid/iso/renderer/urn.rb:15:in `prerender'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-core-1.12.3/lib/pubid/core/renderer/base.rb:26:in `render_base_identifier'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-iso-0.7.4/lib/pubid/iso/renderer/urn.rb:21:in `render'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/pubid-iso-0.7.4/lib/pubid/iso/identifier/base.rb:203:in `urn'
        from (irb):7:in `<main>'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/gems/irb-1.11.1/exe/irb:9:in `<top (required)>'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/irb:25:in `load'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/irb:25:in `<main>'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `eval'
        from /Users/andrej/.rvm/gems/ruby-3.2.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by andrew2net** [comment]
@mico can you release the PR?
